### ISSUE TITLE
Make gghdr ready for CRAN

### ISSUE THREAD

**Issue by Sayani07** [numbats/numbathackathon#11]
Package `gghdr` which helps to visualize Highest Density Regions (HDR) using ggplot2 was developed as a part of rOpenSci 2019. Other authors of the package are Mitchell O'Hara-Wild, Stephen Pearce, Ryo Nakagawara, Darya Vanichkina, Emi Tanaka and Thomas Fung. To make it CRAN ready:

- write more tests
- close issues regarding bugs in functions
-  improve Vignette and README
-  travis CI integration

**Comment by Sayani07** [comment]
The github link of the project : https://github.com/ropenscilabs/gghdr

**Comment by mitchelloharawild** [comment]
No need for travis, we're already set up with GitHub actions.
I've just added code coverage to the CI so you can check the test coverage now.
