### ISSUE TITLE
2023 planning

### ISSUE THREAD

**Issue by dicook** [numbats/numbathackathon#14]
Who's coming:

Di
Rob (car)
Mitch
Xiaoqian
Cynthia
Jayani
Emi
Sherry
Patrick
Harriet (car)
Nuwani
Michael (car)
Fin (Car)

**Comment by dicook** [comment]
- Dinner 1: XXX, XXX
- Breakfast 1: XXX, XXX
- Lunch: XXX, XXX
- Dinner 2: XXX, XXX
- Breakfast 2: XXX, XXX

**Comment by dicook** [comment]
Cleanup:

- Dinner 1: XXX, XXX
- Breakfast 1: XXX, XXX
- Lunch: XXX, XXX
- Dinner 2: XXX, XXX
- Breakfast 2: XXX, XXX

**Comment by cynthiahqy** [comment]
I'm happy to do cook and clean up Dinner 1 if someone wants to pair up?

**Comment by mitchelloharawild** [comment]
Dietry needs:
* Mitch: Vegetarian, sesame allergy
