### ISSUE TITLE
teachr/moodlequiz: R Markdown / Quarto formats for LMS platforms

### ISSUE THREAD

**Issue by mitchelloharawild** [numbats/numbathackathon#15]
Development started here: https://github.com/numbats/teachr

It would be great to get this package on CRAN, and switch out the use of the exams package for our own output formats compatible with Moodle's XML and other widely used LMS.

@emitanaka

**Comment by emitanaka** [comment]
I've actually ported it out to [https://github.com/numbats/moodlequiz](https://github.com/numbats/moodlequiz) so development should be in that repo. Tagging @thomas-fung and @iris-yi-jiang who's doing the testing and implementation at MQ.
