### ISSUE TITLE
NUMBATs website

### ISSUE THREAD

**Issue by dicook** [numbats/numbathackathon#19]
Refresh/update content.

**Comment by robjhyndman** [comment]
Convert to quarto

**Comment by robjhyndman** [comment]
Existing website at https://github.com/numbats/numbats-website

**Comment by robjhyndman** [comment]
New website here: https://github.com/robjhyndman/numbats-quarto-website

**Comment by cynthiahqy** [comment]
For grouping current/alumni/visitor profiles into subfolders
```bash
for x in $(grep -l "Visitor" **/index.qmd); do mv ${x%/*} visitor/${x%/*}; done;
```

**Comment by cynthiahqy** [comment]
A good reference for people listings: https://github.com/jmgirard/affcomlab/blob/main/people.qmd

**Comment by cynthiahqy** [comment]
maybe Quarto listing template: https://github.com/quarto-dev/quarto-cli/tree/08ccbe0f5a56ac030e926dccec9573ca3399955e/src/resources/projects/website/listing

**Comment by robjhyndman** [comment]
Website now uses quarto: [numbat.space](https://numbat.space)
