### ISSUE TITLE
Add quarto template functions to monash package

### ISSUE THREAD

**Issue by robjhyndman** [numbats/numbathackathon#22]
Enable monash quarto templates to be added via the Rstudio template interface.

Monash package at https://github.com/numbats/monash

Quarto templates: https://robjhyndman.com/hyndsight/quarto_templates.html

**Comment by emitanaka** [comment]
Quarto template here: https://github.com/numbats/monash/tree/master/inst/rmarkdown/templates/revealjs

**Comment by emitanaka** [comment]
First try done

**Comment by cynthiahqy** [comment]
Superseded by #37 and https://github.com/quarto-monash accessible via https://numbat.space/projects.html
