### ISSUE TITLE
Create an R package containing Olympics data

### ISSUE THREAD

**Issue by robjhyndman** [numbats/numbathackathon#25]
A starting point is https://github.com/rgriff23/Olympic_history

See also https://cran.r-project.org/web/packages/OlympicRshiny/index.html

**Comment by mitchelloharawild** [comment]
Did a bit of digging into `olympics.com` which has changed a fair bit from last time I looked. Seems possible to get the data directly from there, but it presents a few challenges.

**Comment by robjhyndman** [comment]
https://github.com/numbats/olympics

**Comment by cynthiahqy** [comment]
Sherry said this is done
