### ISSUE TITLE
Posit Table contest 2024 submission

### ISSUE THREAD

**Issue by janithwanni** [numbats/numbathackathon#35]
The posit table contest deadline is on the 14th of June. 

As a demonstration or vignette of #34 or any other dataset that has a social impact, we can create a table using either `{gt}`, `{reactable}`, `{ggplot}` or any other tool. 

The resulting table should be submittable to the Posit Table contest and if needed can be used as material for blog posts or to start a discussion on the topic covered by the table

**Comment by cynthiahqy** [comment]
@janithwanni & @freierson worked on https://github.com/freierson/coffee-table
