### ISSUE TITLE
Teaching / Slidecraft: Establishing some good CSS templates and workflow

### ISSUE THREAD

**Issue by njtierney** [numbats/numbathackathon#4]
At the NUMBAT hack I'm hoping to try and streamline some of my teaching slides

For example, I find myself doing the following when I create a set of teaching slides:

- Copy the previous week's folder
- Rip out most of the content except for the opening slide
- Start writing lecture slides
- Tweak CSS for that given week
- Post slides up online
- work out how to create a PDF of the slides
- post that up online

I think instead I would like to:

- Have a command to initialize a template of a given week (something like `ida::lecture_template(dir = "week_2")` would create:
  - A folder called "week_2"
  - A file called "week_2.Rmd"
- Have a centralised CSS file
- Have a relatively simple process to generate the PDF and also generate a chunk of text to copy and paste into the website (I think @emitanaka has a nice workflow with reading in a CSV into a website for this as well)

**Comment by njtierney** [comment]
Also keen to help create / make public some Rstudio snippets I use when generating slide content / other handy functions for this.

**Comment by njtierney** [comment]
- how to make the slides available offline

**Comment by emitanaka** [comment]
Further to this, the template from Wild Caught Data is available publicly [here](https://github.com/emitanaka/MBATemplate)
