### ISSUE TITLE
Adding basic password protection to quarto sites --> `staticrypt` + GitHub Actions

### ISSUE THREAD

**Issue by cynthiahqy** [numbats/numbathackathon#41]
Quarto sites are fun and great, but some sort of password protection would be handy -- probably doesn't need to be full-on authentication via Google login or similar. Some possibilities to explore:

- Netlify Identity: https://docs.netlify.com/security/secure-access-to-sites/identity/

Related to a previous attempt last year #31 with OAuth

**Comment by cynthiahqy** [comment]
- https://www.thomasvantuycom.com/writing/password-protected-pages-on-netlify/
- https://github.com/robinmoisson/staticrypt
- https://answers.netlify.com/t/support-guide-access-control-options-for-your-netlify-sites/31289

**Comment by robjhyndman** [comment]
A solution is provided here: https://github.com/robjhyndman/quarto-password

**Comment by cynthiahqy** [comment]
@robjhyndman page not found at that link -- I think intentional; maybe you meant to link to the deployed site???

**Comment by robjhyndman** [comment]
Oops. I still had it private. It should be visible now.

**Comment by cynthiahqy** [comment]
what's the password?

**Comment by cynthiahqy** [comment]
I think the password is.. `password`, but when I type it in and press decrypt nothing happens (on safari or Firefox..)

**Comment by robjhyndman** [comment]
Hmm. It's working on Chrome and Vivaldi. But it also doesn't work on Firefox for me. Maybe the javascript is being blocked?

**Comment by robjhyndman** [comment]
Also working on Microsoft Edge.

**Comment by robjhyndman** [comment]
Working now on Firefox

**Comment by cynthiahqy** [comment]
@harriet-mason Here are instructions for adding it to an existing quarto site: https://github.com/robjhyndman/quarto-password/issues/1#issue-2327782087

**Comment by robjhyndman** [comment]
Completed via the https://github.com/robjhyndman/quarto-password/ package
