### ISSUE TITLE
Tools for visualization of multivariate spatiotemporal data

### ISSUE THREAD

**Issue by emdodwell** [numbats/numbathackathon#7]
I am collaborating with Di on the development of a Shiny app for visualization of multivariate spatiotemporal data. Key themes I'll be focusing on during this NUMBAT hackathon include:
- familiarization with geospatial packages and best practices for mapping in R
- representation of longitudinal data
- linked plots to connect them and re-focus attention on each component

I'll be looking at data of the Australian bushfires to get started. Monthly and daily data files of hotspots are available from JAXA's Himawari-8 FTP server. You must request a research login here: https://www.eorc.jaxa.jp/ptree/registration_top.html

Files can then be downloaded from: ftp://ftp.ptree.jaxa.jp/pub/himawari/L3/WLF/bet

Start with monthly file from January 2020: ftp://ftp.ptree.jaxa.jp/pub/himawari/L3/WLF/bet/202001/monthly/

**Comment by dicook** [comment]
Interested in. helping with this too

**Comment by njtierney** [comment]
[geospatial plotting paper](https://www.frontiersin.org/articles/10.3389/fneur.2019.00743/full?&utm_source=Email_to_authors_&utm_medium=Email&utm_content=T1_11.5e1_author&utm_campaign=Email_publication&field=&journalName=Frontiers_in_Neurology&id=462500)

**Comment by nspyrison** [comment]
Keen. have a leaflet kernel started at: https://github.com/nspyrison/NSW_bushfires

**Comment by emdodwell** [comment]
Repo: https://github.com/emdodwell/hotspots

**Comment by emdodwell** [comment]
Column definitions are available in ftp://ftp.ptree.jaxa.jp/pub/H8_WLF_format.txt
