### ISSUE TITLE
Finish rcademy and get it ready for CRAN

### ISSUE THREAD

**Issue by robjhyndman** [numbats/numbathackathon#8]
At the ozunconf in 2019 we started developing the Rcademy package https://github.com/ropenscilabs/Rcademy. It is not yet finished, and does not pass CRAN checks. Also there are some design issues that need thinking about.

It would be great to get it to the point where it is usable and on CRAN.

This could involve including data as discussed in #2.

**Comment by njtierney** [comment]
Happy to help chime in on this one.

**Comment by njtierney** [comment]
![image](https://user-images.githubusercontent.com/6488485/74807965-de8b4100-533d-11ea-88f0-e5f00c786f78.png)
