### ISSUE TITLE
Establish some github actions recipes to run spell check and compile rmd docs

### ISSUE THREAD

**Issue by njtierney** [numbats/numbathackathon#9]
There was some great work on this at the ozunconf 2019 - https://github.com/ropenscilabs/actions_sandbox

The goal is to have a template to make it so you can set up a project that will, upon pushing to github

- Run spell check
- Compile the Rmd file
- Potentially deploy the paper under docs/index.html so you can serve the paper at: USERNAME.github.io/REPOSITORY

Prior art: https://github.com/andycasey/paper-maker

**Comment by mitchelloharawild** [comment]
For spell check, my approach has been to include it in the package tests.
https://github.com/tidyverts/fable/blob/master/tests/testthat/test-spelling.R

This script could definitely be improved though!
